# -*- coding: utf-8 -*-
"""
/***************************************************************************
 TreeSegmentation
                                 A QGIS plugin
 Tree segmentation from aerial point cloud data.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2022-01-05
        copyright            : (C) 2022 by TSFAP Capstone
        email                : sam@foltz.dev
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load TreeSegmentation class from file TreeSegmentation.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .treesegmentation import TreeSegmentation
    return TreeSegmentation(iface)
