# -*- coding: utf-8 -*-
"""
/***************************************************************************
 Example
                                 A QGIS plugin
 just an example
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2021-11-11
        copyright            : (C) 2021 by Mark Gekelman
        email                : gekelmam@oregonstate.edu
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""

__all__ = ["treesegmentation"]

# noinspection PyPep8Naming


def classFactory(iface):  # pylint: disable=invalid-name
    """Load Example class from file Example.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .example import Example
    return Example(iface)
